# Generated by Django 5.2.13 on 2026-05-01 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=20)),
                ('chain', models.CharField(choices=[('ETH', 'Ethereum'), ('BSC', 'Binance Smart Chain'), ('POLY', 'Polygon'), ('SOL', 'Solana')], max_length=10)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('liquidity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('volume_24h', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiquidityPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve_a', models.DecimalField(decimal_places=8, max_digits=20)),
                ('reserve_b', models.DecimalField(decimal_places=8, max_digits=20)),
                ('fee_percent', models.DecimalField(decimal_places=2, default=0.3, max_digits=5)),
                ('chain', models.CharField(max_length=10)),
                ('uptime', models.DecimalField(decimal_places=2, default=98.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools_a', to='trades.token')),
                ('token_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools_b', to='trades.token')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_in', models.DecimalField(decimal_places=8, max_digits=20)),
                ('amount_out', models.DecimalField(decimal_places=8, max_digits=20)),
                ('trade_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('SWAP', 'Swap')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('slippage', models.DecimalField(decimal_places=2, default=0.5, max_digits=5)),
                ('gas_fee', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('wallet_address', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('token_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_in', to='trades.token')),
                ('token_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_out', to='trades.token')),
            ],
        ),
    ]
